apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uploadme-app
  template:
    metadata:
      labels:
        app: uploadme-app
    spec:
       tolerations:
        - key:   "critical"
          value:  "true"
          effect: "NoSchedule"
      containers:
        - name: back-end
          image: 307797441431.dkr.ecr.us-east-1.amazonaws.com/kubernetes-cluster:latest
          ports:
          - containerPort: 8081
            resources:
              limits:
                 cpu: 500m
              requests:
                 cpu: 200m
