
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upg-loadme-app
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-demo
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

